### ISSUE TITLE
Collaboration with doom-community-themes

### ISSUE THREAD

**Issue by flatwhatson** [ema2159/muse-themes#3]
Hi, it seems that this project and [doom-community-themes](https://github.com/Emiller88/emacs-doom-community-themes) are trying to achieve the same objective!  You should know that the `doom-community-themes` package has been set up with Henrik's blessing in preparation for the next major release of `doom-themes`.

It looks like you've already been working on some improvements to these themes, it would benefit everyone if we worked together on the community repo.  We will happily accept your PRs!

Also, please come and join us on the [official Doom Emacs discord server](https://discord.gg/bcZ6P3y) to be involved in the future planning for `doom-themes` and `doom-community-themes`.

**Comment by ema2159** [comment]
Hi! The problem with this is that I've found it's too tedious to be constantly submitting PRs to upload new themes or to do modifications, so I think I'd rather implement my own package, it's less messy and hopefully both packages could provide different theme options and give the community more options

**Comment by ema2159** [comment]
By the way, @ianpan870102, what do you think about this? Shall we continue with this or should we join them?

**Comment by flatwhatson** [comment]
That is understandable, the `doom-themes` package has been slow to accept fixes and new themes, and this has surely frustrated many people who want to contribute.  This is exactly why `doom-community-themes` has been created!  We have a number of collaborators with more attention to give to reviewing and merging PRs.

The invitation remains open, and we hope you'll reconsider.

If not, no worries and best of luck!

**Comment by ema2159** [comment]
I'll talk it with my colleague and from there we can make the decision

**Comment by ianyepan** [comment]
@ema2159 Apologies for the late reply, I've been rather busy lately.

> By the way, @ianpan870102, what do you think about this? Shall we continue with this or should we join them?

I'm actually quite open to contributing to any package, so long as the repo could be actively maintained. I'm also partially bothered by the idea that there are so many "duplicate" packages on MELPA, and I sometimes hope that similar packages can merge to one. I understand that some people might think that this gives the users more choices, but truth be told I think the majority of the people just want a single entry point for one particular target.

Of course, this is somehow the nature of open source projects, and the way MELPA maintainers accept packages isn't something we could influence that easily anyways.

If muse-themes and doom-community-themes are sharing the same core, I think people could easily contribute to both by using the same file. As for the duplication, I guess it's up to the owners to work it out -- as for me as a contributor, I try to keep a more open mind, so I'm happy with whatever the outcome is.

**Comment by ema2159** [comment]
@flatwhatson I have two major concerns:
- My Treemacs theme: I implemented a Treemacs theme slightly less minimalistic than dooms, could that be added to the package?
- Becoming a collaborator: I would not ask to become a collaborator from day to night, but let say if me an Ian implemented let say 5 or more themes each, would you be open to make us collaborators? I think that would be a good idea for having certain maintainers assigned for certain themes.

**Comment by ema2159** [comment]
> @ema2159 Apologies for the late reply, I've been rather busy lately.
> 
> > By the way, @ianpan870102, what do you think about this? Shall we continue with this or should we join them?
> 
> I'm actually quite open to contributing to any package, so long as the repo could be actively maintained. I'm also partially bothered by the idea that there are so many "duplicate" packages on MELPA, and I sometimes hope that similar packages can merge to one. I understand that some people might think that this gives the users more choices, but truth be told I think the majority of the people just want a single entry point for one particular target.
> 
> Of course, this is somehow the nature of open source projects, and the way MELPA maintainers accept packages isn't something we could influence that easily anyways.
> 
> If muse-themes and doom-community-themes are sharing the same core, I think people could easily contribute to both by using the same file. As for the duplication, I guess it's up to the owners to work it out -- as for me as a contributor, I try to keep a more open mind, so I'm happy with whatever the outcome is.

I'm also really concerned with duplication, the idea that Mr. Lissner has now with doom-themes and doom-community-themes is to encourage the use of a single API in order to prevent theme duplication. But I find really tedious to maintain a theme constantly PRing a repo (in this case doom-community-themes), so a really important aspect for me in this decision is the possibility of becoming collaborators once we've proven that we're responsible enough to do so. I personally have very high coding and documentation standards and I know that Ian too, so I'd really like to know if doom-community-themes owners are open on letting us become collaborators.

**Comment by jwintz** [comment]
Hi, being myself part of the community and a `doom-themes` contributor, I must add:

- `doom`’s author makes a great job on a daily basis, and is, *highly* responsive
- `doom`‘s spectrum is that wide, no one can answer that quickly
- as one of the first users, years after, I’m still stunned about how many things I learn just by upgrading

Now for `muse`:

- your expectation is great
- `doom-community-themes` is maintained by an active and skilled user of `doom`
- `doom-community-themes` will have credit to be more responsive for that kind of matter

On a personal level:

- Please join the community: you’ll have a warm welcome
- Give credit to `Henrik` in your headers, cause most of it is a copy paste then `query-replace`

As for what follows up:

- `doom-core` is most likely subject to change in the near future.
- Be part of the community and enjoy the goodness !

Looking forward to meet U on Doom’s discord server.

**Comment by ema2159** [comment]
> Hi, being myself part of the community and a `doom-themes` contributor, I must add:
> 
> * `doom`’s author makes a great job on a daily basis, and is, _highly_ responsive
> * `doom`‘s spectrum is that wide, no one can answer that quickly
> * as one of the first users, years after, I’m still stunned about how many things I learn just by upgrading
> 
> Now for `muse`:
> 
> * your expectation is great
> * `doom-community-themes` is maintained by an active and skilled user of `doom`
> * `doom-community-themes` will have credit to be more responsive for that kind of matter
> 
> On a personal level:
> 
> * Please join the community: you’ll have a warm welcome
> * Give credit to `Henrik` in your headers, cause most of it is a copy paste then `query-replace`
> 
> As for what follows up:
> 
> * `doom-core` is most likely subject to change in the near future.
> * Be part of the community and enjoy the goodness !
> 
> Looking forward to meet U on Doom’s discord server.

Yes I understand, I Henrik has a lot to deal with, so that's why I decided to start this package, but I wasn't aware of `doom-community-themes` and now being aware of its existence continuing `muse` seems a little bit pointless giving its redundant.
 Having said that, I'd like to be part of `doom-community-themes`, and I was planning to port many themes but doing so by submitting a hundred PRs seems really tedious, and giving maintenance to those themes could be even worse.
I'd like to know then if I'd be given a chance of becoming a collaborator. I can say that I've contributed to many many Emacs packages (base16, Hydra, Dashboard etc) and I even own `centaur-tabs` which has rised really quickly, so what's more important for me to decide is to know if I'd have the chance to become a collaborator at `doom-community-themes` and what do I have to do.

**Comment by jwintz** [comment]
Edmund will say, but as I understand the situation, you’re more than welcome ! Cheers.

**Comment by jwintz** [comment]
As a proof of my enthusiasm, please find attached, a first attempt (5 mins, no thinking) at porting `wilmersdorf` to `doom`: https://github.com/jwintz/doom/blob/develop/%2Bui-theme.el.

Very sexy already. To be reviewed. Thanks to the author.

![28B36D81-AB3E-4B89-9AD8-05745308D094](https://user-images.githubusercontent.com/3277054/61832471-86f12980-ae71-11e9-89a8-53a54e849761.png)

**Comment by ema2159** [comment]
> As a proof of my enthusiasm, please find attached, a first attempt (5 mins, no thinking) at porting `wilmersdorf` to `doom`: https://github.com/jwintz/doom/blob/develop/%2Bui-theme.el.
> 
> Very sexy already. To be reviewed. Thanks to the author.
> 
> ![28B36D81-AB3E-4B89-9AD8-05745308D094](https://user-images.githubusercontent.com/3277054/61832471-86f12980-ae71-11e9-89a8-53a54e849761.png)

Wilmesdorf is @ianpan870102 and it's indeed an incredibly sexy theme. I think the best option here is to archive this repo. I'll talk with Edmund to see how we can join.
